image: ubuntu:18.04

before_script:
  - apt-get update && apt-get install -y --no-install-recommends -qq apt-utils
  - apt-get install -y -qq sshpass
  - apt-get install -y -qq nodejs
  - nodejs --version
  - apt-get install -y -qq npm
  - npm --version
  - apt-get install -y -qq yarn
  - yarn --version

deploy_stage:
  stage: deploy
  environment: Staging
  only:
    - master
  script:
    # CLEAR OPENCART
    - rm ./API ./PLAN ./MOVE.todo ./melle-new.sublime-project -f

    # CONFIG FILES
    - rm ./config.php ./admin/config.php -f
    - mv ./config.test.php ./config.php
    - mv ./admin/config.test.php ./admin/config.php

    # YARN RUN
    - rm ./yarn.lock ./mix-manifest.json -f
    - yarn install
    - yarn run prod
    - yarn run prod-import1c
    - yarn run prod-offersadmin
    - yarn run prod-offers

    # CLEAR AFTER YARN
    - rm -R ./node_modules/ -f
    - rm ./yarn.lock -f
    - rm ./package.json -f
    - rm ./webpack* -f
    - rm -R ./catalog/view/javascript/melle/src/ -f
    - rm -R ./admin/view/javascript/import_1c/src/ -f
    - rm -R ./admin/view/javascript/super_offers/src/ -f
    - rm -R ./admin/view/javascript/super_offers_admin/src/ -f

    # CLONE TO PROD
    - sshpass -V
    - export SSHPASS=$K8S_SECRET_SSH
    - sshpass -e ssh -o stricthostkeychecking=no web@91.226.80.187 "bash -s" < ./build/backup.sh
    - rm -R ./build/ -f
    - sshpass -e scp -o stricthostkeychecking=no -r . web@91.226.80.187:/home/web/work.melle.online/www