image: ubuntu:18.04

# cache:
#   paths:
#     - node_modules/

before_script:
  - apt-get update && apt-get install -y --no-install-recommends -qq apt-utils
  # - apt-get install -qq curl
  # - apt-get install -qq gnupg
  # - apt-get install -qq gnupg1
  # - apt-get install -qq gnupg2
  # - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
  # - echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
  - apt-get install -y -qq sshpass
  # - apt-get install -y -qq nodejs
  # - apt-get install -y -qq npm
  # - apt-get install -y -qq yarn
  # - yarn --version

deploy_stage:
  stage: deploy
  environment: Staging
  only:
    - master
  script:
    # CLEAR OPENCART
    - rm ./API ./PLAN ./MOVE.todo ./melle-new.sublime-project -f

    # CONFIG FILES
    - rm ./config.php ./admin/config.php -f
    - mv ./config.test.php ./config.php
    - mv ./admin/config.test.php ./admin/config.php

    # YARN RUN
    # - rm ./yarn.lock ./mix-manifest.json -f
    # - yarn install
    # - yarn run prod
    # - yarn run prod-import1c
    # - yarn run prod-offersadmin
    # - yarn run prod-offers

    # CLEAR AFTER YARN
    - rm ./yarn.lock -f
    - rm ./package.json -f
    - rm ./webpack*
    - rm -R ./catalog/view/javascript/melle/src/ -f
    - rm -R ./admin/view/javascript/import_1c/src/ -f
    - rm -R ./admin/view/javascript/super_offers/src/ -f
    - rm -R ./admin/view/javascript/super_offers_admin/src/ -f

    # CLONE TO PROD
    - sshpass -V
    - export SSHPASS=$K8S_SECRET_SSH
    - sshpass -e stricthostkeychecking=no ssh web@91.226.80.187 "bash -s" < ./backup.sh

    # - sshpass  mv  -v ~/Downloads/* ~/Videos/
    # - sshpass -e scp -o stricthostkeychecking=no -r ./index.php web@91.226.80.187:/home/web/work.melle.online/www