image: registry.gitlab.com/pro-hamster/ci-scripts:latest

before_script:
  - apt-get -qq update < /dev/null > /dev/null
  - apt-get -qq install p7zip-full < /dev/null > /dev/null
  - apt-get -qq install -y sshpass < /dev/null > /dev/null

deploy_stage:
  stage: deploy
  # environment: Staging
  only:
    - master
  script:
    - chmod +x ./build/build_.sh
    - ./build/build_.sh